version: '3'

services:
  postgres:
    image: postgres:15.1
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1691


  backend:
    image: margaritavak/test_task_back:latest
    ports:
      - 3001:3001
    depends_on:
      - postgres

  frontend:
    image: margaritavak/test_task:latest
    ports:
      - 4200:4200
    depends_on:
      - backend

volumes:
  database: {}
